### ISSUE TITLE
page definition documentation

### ISSUE THREAD

**Issue by josecvega** [SmartThingsCommunity/Documentation#404]
On Page Definition, it was understood that in order to move to the next page we could use nextPage attribute, but i didn't see a way for the user to go to the previous page. I tried prevPage, previousPage and backPage but none seem to work. Curious if there exist a way.
I am also not sure if this is the best place to ask this question.

**Comment by jimmyjames** [comment]
You don't need to specify anything for the previous page. Basically the next page informs the mobile app what page to load when clicking next (i.e. it doesn't actually do any navigation it just specifies what should happen when clicking next). The previous page doesn't need to be specified because the app will know what the previously displayed page is.

**Comment by josecvega** [comment]
Thanks. It might be an issue with the simulator. The simulator correctly handled the Next button, but pressing the Back didn't correctly handle switching to the previous page.

**Comment by jimmyjames** [comment]
Might be an issue with the simulator; try in the app to make sure.
